import Box from '@mui/material/Box';
import * as React from 'react';
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry';

import type { Metadata } from "next";
import VibesAppBar from './components/VibesNavBar';


export const metadata: Metadata = {
  title: "Vibes Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <VibesAppBar />
          <Box
            component="main"
            sx={{
              flexGrow: 1,
              bgcolor: 'background.default',
            }}
          >
            {children}
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
