import "./globals.css";
import { Metadata } from 'next'

import AppProviders from "../components/AppProviders";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthClientProvider from "@/app/context/next-auth-client-provider"
import { getServerSession } from "next-auth";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <meta
        name="viewport"
        content="minimum-scale=1, initial-scale=1, width=device-width"
      />
      <body>
        <NextAuthClientProvider session={session}>
          <AppProviders>
            <div className="p-6">{children}</div>
          </AppProviders>
        </NextAuthClientProvider>
      </body>
    </html>
  );
}
