import {
  BookedHoursPerWeek,
  BookingType,
  CompetenceReadModel,
  ConsultantReadModel,
  Degree,
  DepartmentReadModel,
  DetailedBooking,
  EngagementPerCustomerReadModel,
  OrganisationReadModel,
  BookingReadModel,
} from "@/api-types";
import { Forecast } from "@/types";

const MockWeeklyBookingReadModel: BookingReadModel = {
  totalHolidayHours: 0,
  totalOverbooking: 0,
  totalPlannedAbsences: 0,
  totalSellableTime: 0,
  totalBillable: 0,
  totalOffered: 0,
  totalVacationHours: 0,
  totalExcludableAbsence: 0,
  totalNotStartedOrQuit: 0,
};
const mockForecast1: Forecast = {
  id: 1,
  month: 0,
  year: 2025,
  forecastValue: 80,
  hasBeenChanged: false,
  valueAddedManually: 0,
};
const mockForecast2: Forecast = {
  id: 2,
  month: 1,
  year: 2025,
  forecastValue: 80,
  hasBeenChanged: false,
  valueAddedManually: 0,
};
const mockForecast3: Forecast = {
  id: 3,
  month: 2,
  year: 2025,
  forecastValue: 50,
  hasBeenChanged: false,
  valueAddedManually: 0,
};
const mockForecast4: Forecast = {
  id: 4,
  month: 3,
  year: 2025,
  forecastValue: 100,
  hasBeenChanged: false,
  valueAddedManually: 0,
};
const mockForecast5: Forecast = {
  id: 5,
  month: 4,
  year: 2025,
  forecastValue: 0,
  hasBeenChanged: true,
  valueAddedManually: 50,
};
const mockForecast6: Forecast = {
  id: 6,
  month: 5,
  year: 2025,
  forecastValue: 70,
  hasBeenChanged: true,
  valueAddedManually: 10,
};

export const MockDepartments: DepartmentReadModel[] = [
  {
    id: "myDepartment",
    name: "My Department",
  },
];

export const MockOrganisations: OrganisationReadModel[] = [
  {
    name: "My Organisation",
    urlKey: "my-org",
  },
];

export const MockEngagements: EngagementPerCustomerReadModel[] = [
  {
    customerId: 1,
    customerName: "TestCustomer",
    engagements: [],
    isActive: false,
  },
];

export const MockCompetences: CompetenceReadModel[] = [
  {
    id: "development",
    name: "Utvikling",
  },
];
const mockDetailedBookings: DetailedBooking[] = [
  {
    bookingDetails: {
      projectName: "Elbil",
      type: BookingType.Booking,
      customerName: "Bil",
      projectId: 1001,
      isBillable: true,
      endDateAgreement: "2025-05-08T00:00:00",
    },
    hours: [
      { week: 202502, hours: 37.5 },
      { week: 202503, hours: 37.5 },
      { week: 202504, hours: 37.5 },
      { week: 202505, hours: 37.5 },
      { week: 202506, hours: 30 },
      { week: 202507, hours: 22.5 },
      { week: 202508, hours: 37.5 },
      { week: 202509, hours: 37.5 },
      { week: 202510, hours: 37.5 },
      { week: 202511, hours: 30 },
      { week: 202512, hours: 30 },
      { week: 202513, hours: 30 },
      { week: 202514, hours: 37.5 },
      { week: 202515, hours: 37.5 },
      { week: 202516, hours: 22.5 },
      { week: 202517, hours: 30 },
      { week: 202518, hours: 30 },
    ],
  },
  {
    bookingDetails: {
      projectName: "Nye nettsider",
      type: BookingType.Offer,
      customerName: "Åkerblå",
      projectId: 208,
      isBillable: false,
      endDateAgreement: "2024-11-29T00:00:00",
    },
    hours: [
      { week: 202502, hours: 0 },
      { week: 202503, hours: 0 },
      { week: 202504, hours: 0 },
      { week: 202505, hours: 0 },
      { week: 202506, hours: 0 },
      { week: 202507, hours: 0 },
      { week: 202508, hours: 0 },
      { week: 202509, hours: 0 },
      { week: 202510, hours: 0 },
      { week: 202511, hours: 7.5 },
      { week: 202512, hours: 7.5 },
      { week: 202513, hours: 7.5 },
      { week: 202514, hours: 0 },
      { week: 202515, hours: 0 },
      { week: 202516, hours: 0 },
      { week: 202517, hours: 0 },
      { week: 202518, hours: 0 },
    ],
  },
];
const mockBookings: BookedHoursPerWeek[] = [
  {
    year: 2025,
    weekNumber: 2,
    sortableWeek: 202502,
    dateString: "06.01 - 10.01",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 3,
    sortableWeek: 202503,
    dateString: "13.01 - 17.01",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 4,
    sortableWeek: 202504,
    dateString: "20.01 - 24.01",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 5,
    sortableWeek: 202505,
    dateString: "27.01 - 31.01",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 6,
    sortableWeek: 202506,
    dateString: "03.02 - 07.02",
    bookingModel: {
      totalBillable: 30,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 7.5,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 7,
    sortableWeek: 202507,
    dateString: "10.02 - 14.02",
    bookingModel: {
      totalBillable: 22.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 15,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 8,
    sortableWeek: 202508,
    dateString: "17.02 - 21.02",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 9,
    sortableWeek: 202509,
    dateString: "24.02 - 28.02",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 10,
    sortableWeek: 202510,
    dateString: "03.03 - 07.03",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 11,
    sortableWeek: 202511,
    dateString: "10.03 - 14.03",
    bookingModel: {
      totalBillable: 30,
      totalOffered: 7.5,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 7.5,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 12,
    sortableWeek: 202512,
    dateString: "17.03 - 21.03",
    bookingModel: {
      totalBillable: 30,
      totalOffered: 7.5,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 7.5,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 13,
    sortableWeek: 202513,
    dateString: "24.03 - 28.03",
    bookingModel: {
      totalBillable: 30,
      totalOffered: 7.5,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 7.5,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 14,
    sortableWeek: 202514,
    dateString: "31.03 - 04.04",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 15,
    sortableWeek: 202515,
    dateString: "07.04 - 11.04",
    bookingModel: {
      totalBillable: 37.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 0,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 16,
    sortableWeek: 202516,
    dateString: "14.04 - 18.04",
    bookingModel: {
      totalBillable: 22.5,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 15,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
  {
    year: 2025,
    weekNumber: 17,
    sortableWeek: 202517,
    dateString: "21.04 - 25.04",
    bookingModel: {
      totalBillable: 30,
      totalOffered: 0,
      totalPlannedAbsences: 0,
      totalExcludableAbsence: 0,
      totalSellableTime: 0,
      totalHolidayHours: 7.5,
      totalVacationHours: 0,
      totalOverbooking: 0,
      totalNotStartedOrQuit: 0,
    },
  },
];
export const MockConsultants: ConsultantReadModel[] = [
  {
    id: 1,
    name: "Test Consultant",
    email: "test@company.io",
    competences: [{ id: "development", name: "Utvikling" }],
    department: { id: "mydepartment", name: "My Department" },
    bookings: [
      {
        year: 2023,
        weekNumber: 10,
        dateString: "",
        bookingModel: MockWeeklyBookingReadModel,
        sortableWeek: 202310,
      },
    ],
    yearsOfExperience: 23,
    detailedBooking: [],
    isOccupied: true,
    graduationYear: 2010,
    degree: Degree.Bachelor,
    forecasts: [
      mockForecast1,
      mockForecast2,
      mockForecast3,
      mockForecast4,
      mockForecast5,
      mockForecast6,
    ],
  },
];

export const MockConsultantsForForecast: ConsultantReadModel[] = [
  {
    id: 1,
    name: "Test Consultant",
    email: "test@company.io",
    competences: [{ id: "development", name: "Utvikling" }],
    department: { id: "mydepartment", name: "My Department" },
    bookings: [
      {
        year: 2023,
        weekNumber: 10,
        dateString: "",
        bookingModel: MockWeeklyBookingReadModel,
        sortableWeek: 202310,
      },
    ],
    yearsOfExperience: 23,
    detailedBooking: [],
    isOccupied: true,
    graduationYear: 2010,
    degree: Degree.Bachelor,
    forecasts: [
      mockForecast1,
      mockForecast2,
      mockForecast3,
      mockForecast4,
      mockForecast5,
      mockForecast6,
    ],
  },
  {
    id: 2,
    name: "2test Consultant",
    email: "test2@company.io",
    competences: [{ id: "development", name: "Utvikling" }],
    department: { id: "mydepartment", name: "My Department" },
    bookings: mockBookings,
    yearsOfExperience: 23,
    detailedBooking: mockDetailedBookings,
    isOccupied: true,
    graduationYear: 2010,
    degree: Degree.Bachelor,
    forecasts: [
      mockForecast1,
      mockForecast2,
      mockForecast3,
      mockForecast4,
      mockForecast5,
      mockForecast6,
    ],
  },
];
